title: Thomas Carman
author:
  name: Thomas Carman

description: >
  Software Engineer | Full-Stack Developer | DevOps Enthusiast
  Building innovative solutions with modern technologies

show_downloads: false
theme: jekyll-theme-hacker
plugins:
  - jekyll-remote-theme
